# Generated by Django 5.2.14 on 2026-05-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='available',
            new_name='active',
        ),
    ]
