# Generated by Django 5.2.14 on 2026-05-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-created'], 'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AddField(
            model_name='chat',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Открытый чат'),
            preserve_default=False,
        ),
    ]
