# Generated by Django 5.2.14 on 2026-05-12 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_llmrequest'),
        ('project', '0005_project_yougile_column_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='chat.chat', verbose_name='Предыдущая версия чата'),
        ),
        migrations.AddField(
            model_name='chat',
            name='version_number',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Открытый чат'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chat',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='project.project'),
        ),
    ]
