# Generated by Django 5.2.14 on 2026-05-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.CharField(default=1, max_length=50, verbose_name='Страна проекта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=1, max_length=255, verbose_name='Описание проекта'),
            preserve_default=False,
        ),
    ]
