# Generated by Django 5.2.14 on 2026-05-11 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_country_project_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
