# Generated by Django 5.2.14 on 2026-05-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_country_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='yougile_column_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='YouGile Column Key'),
        ),
    ]
