# Generated by Django 5.2.14 on 2026-05-12 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0005_project_yougile_column_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название агента')),
                ('description', models.TextField(verbose_name='Описание агента')),
                ('skill', models.TextField(verbose_name='Системный промпт')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='project.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Агент',
                'verbose_name_plural': 'Агенты',
                'ordering': ['-created'],
            },
        ),
    ]
